# Generated by Django 5.2.5 on 2025-08-27 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('owner', 'name')},
        ),
    ]
