# Generated by Django 5.2.5 on 2025-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Sonstiges', max_length=100),
        ),
    ]
